# Generated by Django 5.1.3 on 2024-12-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primeiro_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='ultimo_nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
