# Generated by Django 5.1.3 on 2024-12-27 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
