# Generated by Django 5.1.3 on 2025-01-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_remove_user_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='image')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.CharField(max_length=200)),
                ('verificado', models.BooleanField(default=False)),
            ],
        ),
    ]
