# Generated by Django 5.1.3 on 2025-01-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contato',
        ),
    ]
