# Generated by Django 5.1.4 on 2025-01-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_rename_contact_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone_celular', models.CharField(max_length=15)),
                ('telefone_comercial', models.CharField(blank=True, max_length=15, null=True)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=9)),
                ('nome_loja', models.CharField(max_length=100)),
                ('categoria_produtos', models.CharField(max_length=50)),
                ('descricao_loja', models.TextField(blank=True, null=True)),
                ('logotipo', models.ImageField(blank=True, null=True, upload_to='vendedores/logotipos/')),
                ('nome_banco', models.CharField(max_length=50)),
                ('numero_conta', models.CharField(max_length=20)),
                ('agencia', models.CharField(max_length=10)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Conta Corrente'), ('poupanca', 'Conta Poupança')], max_length=10)),
                ('titular_conta', models.CharField(max_length=100)),
                ('aceite_termos', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
