# Generated by Django 5.1.3 on 2024-12-12 03:47

import core.models
import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=10, prefix='cat', unique=True)),
                ('titulo', models.CharField(default='Alimentos', max_length=100)),
                ('imagem', models.ImageField(default='categoria.jpg', upload_to='categoria')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='Endereco',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereço'},
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='address',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='user',
            new_name='usuario',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='date',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='usuario',
        ),
        migrations.CreateModel(
            name='ItensPedidoCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_fatura', models.CharField(max_length=200)),
                ('status_produto', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('imagem', models.CharField(max_length=200)),
                ('qtd', models.IntegerField(default=0)),
                ('preco', models.DecimalField(decimal_places=2, default=1.99, max_digits=999999999)),
                ('total', models.DecimalField(decimal_places=2, default=1.99, max_digits=999999999)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itens do Pedido do Carrinho',
            },
        ),
        migrations.CreateModel(
            name='PedidoCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, default=1.99, max_digits=999999999)),
                ('status_pagamento', models.BooleanField(default=False)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('status_produto', models.CharField(choices=[('processing', 'Em Processamento'), ('shipped', 'Enviado'), ('delivered', 'Entregue')], default='processing', max_length=30)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pedidos do Carrinho',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=10, prefix='', unique=True)),
                ('titulo', models.CharField(default='Lima Laranja', max_length=100)),
                ('imagem', models.ImageField(default='produto.jpg', upload_to=core.models.user_directory_path)),
                ('descricao', models.TextField(blank=True, default='Este é o produto', null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=1.99, max_digits=999999999)),
                ('preco_antigo', models.DecimalField(decimal_places=2, default=2.99, max_digits=999999999)),
                ('especificacoes', models.TextField(blank=True, null=True)),
                ('status_produto', models.CharField(choices=[('draft', 'Rascunho'), ('disabled', 'Desativado'), ('rejected', 'Rejeitado'), ('in_review', 'Em Revisão'), ('published', 'Publicado')], default='in_review', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('em_estoque', models.BooleanField(default=False)),
                ('destaque', models.BooleanField(default=False)),
                ('digital', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='sku', unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.categoria')),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tags')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='ImagemProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagens', models.ImageField(default='produto.jpg', upload_to='imagens-produto')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.produto')),
            ],
            options={
                'verbose_name_plural': 'Imagens do Produto',
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.TextField()),
                ('classificacao', models.IntegerField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default=None)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.produto')),
            ],
            options={
                'verbose_name_plural': 'Avaliações do Produto',
            },
        ),
        migrations.AddField(
            model_name='wishlist',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.produto'),
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', length=10, max_length=10, prefix='ven', unique=True)),
                ('titulo', models.CharField(default='Organyx', max_length=100)),
                ('imagem', models.ImageField(default='vendedor.jpg', upload_to=core.models.user_directory_path)),
                ('descricao', models.TextField(blank=True, default='Sou um vendedor de sucesso', null=True)),
                ('endereco', models.CharField(default='Rua Principal', max_length=100)),
                ('contato', models.CharField(default='+55 (12) 12345 6789', max_length=100)),
                ('tempo_resp_chat', models.CharField(default='100', max_length=100)),
                ('entrega_no_prazo', models.CharField(default='100', max_length=100)),
                ('avaliacao_autenticidade', models.CharField(default='100', max_length=100)),
                ('dias_devolucao', models.CharField(default='100', max_length=100)),
                ('periodo_garantia', models.CharField(default='100', max_length=100)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
        migrations.DeleteModel(
            name='CartOrderItems',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
