# Generated by Django 5.1.3 on 2024-12-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_categoria_rename_address_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tags',
        ),
    ]
