# Generated by Django 5.1.3 on 2024-12-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_produto_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaoproduto',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='pedidocarrinho',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='usuario',
            new_name='user',
        ),
    ]
