# Generated by Django 5.1.3 on 2024-12-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_produto_vendedor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='usuario',
            new_name='user',
        ),
    ]
