# Generated by Django 5.1.3 on 2024-12-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_usuario_vendedor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
