# Generated by Django 5.1.3 on 2024-12-15 19:42

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_vendedor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='capa_imagem',
            field=models.ImageField(default='capa.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
