# Generated by Django 5.1.3 on 2024-12-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vendedor_capa_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemproduto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='p_imagem', to='core.produto'),
        ),
    ]
