# Generated by Django 5.1.3 on 2024-12-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_imagemproduto_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_fab',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_estoque',
            field=models.CharField(blank=True, default='10', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(blank=True, default='Orgânico', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.CharField(blank=True, default='100 dias', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='titulo',
            field=models.CharField(blank=True, default='Lima Laranja', max_length=100, null=True),
        ),
    ]
