# Generated by Django 5.1.3 on 2024-12-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_produto_data_fab_produto_qtd_estoque_produto_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
