# Generated by Django 5.1.3 on 2024-12-17 06:39

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_produto_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Este é o produto.', null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='especificacoes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, default='Sou um vendedor de sucesso', null=True),
        ),
    ]
