# Generated by Django 5.1.3 on 2024-12-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_produto_descricao_alter_produto_especificacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='classificacao',
            field=models.IntegerField(choices=[('1', '★☆☆☆☆☆'), ('2', '★★☆☆☆☆'), ('3', '★★★☆☆☆'), ('4', '★★★★☆☆'), ('5', '★★★★★☆'), ('6', '★★★★★★')], default=None),
        ),
    ]
