# Generated by Django 5.1.3 on 2024-12-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_avaliacaoproduto_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='classificacao',
            field=models.IntegerField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default=1),
        ),
    ]
