# Generated by Django 5.1.3 on 2024-12-18 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_avaliacaoproduto_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaoproduto',
            old_name='avaliacao',
            new_name='review',
        ),
    ]
