# Generated by Django 5.1.3 on 2024-12-18 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_rename_avaliacao_avaliacaoproduto_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaoproduto',
            old_name='review',
            new_name='avaliacao',
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='classificacao',
            field=models.IntegerField(choices=[('1', '★☆☆☆☆'), ('2', '★★☆☆☆'), ('3', '★★★☆☆'), ('4', '★★★★☆'), ('5', '★★★★★')], default=None),
        ),
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
