# Generated by Django 5.1.3 on 2024-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_rename_review_avaliacaoproduto_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='classificacao',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None),
        ),
    ]
