# Generated by Django 5.1.3 on 2024-12-21 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_avaliacaoproduto_classificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaoproduto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='core.produto'),
        ),
    ]
