# Generated by Django 5.1.3 on 2024-12-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_avaliacaoproduto_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
