# Generated by Django 5.1.3 on 2024-12-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_antigo',
            field=models.DecimalField(decimal_places=2, default=2.99, max_digits=10),
        ),
    ]
