# Generated by Django 5.1.3 on 2025-01-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_produto_preco_alter_produto_preco_antigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedidocarrinho'),
        ),
    ]
