# Generated by Django 5.1.3 on 2025-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_itenspedidocarrinho_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='localidade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
