# Generated by Django 5.1.3 on 2025-01-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_endereco_endereco_endereco_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
