# Generated by Django 5.1.3 on 2025-01-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_endereco_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='address_type',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
    ]
