# Generated by Django 5.1.3 on 2025-01-02 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_endereco_address_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='address_type',
        ),
    ]
