# Generated by Django 5.1.3 on 2025-01-09 20:53

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_endereco_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='badges',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hot', 'Hot'), ('new', 'Novo'), ('sale', 'Promoção'), ('best', 'Melhor')], max_length=17, null=True),
        ),
    ]
