# Generated by Django 5.1.3 on 2025-01-09 21:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_produto_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='badges',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hot', 'Destaque'), ('new', 'Novo'), ('sale', 'Promoção'), ('bestseller', 'Mais Vendido'), ('trending', 'Em Alta'), ('recommended', 'Recomendado'), ('exclusive_deal', 'Oferta Exclusiva'), ('free_shipping', 'Frete Grátis'), ('best_price', 'Melhor Preço'), ('just_arrived', 'Recém-Chegado'), ('limited_edition', 'Edição Limitada'), ('organic', 'Orgânico'), ('handmade', 'Feito à Mão'), ('locally_made', 'Produzido Localmente'), ('warranty', 'Garantia'), ('certified', 'Certificado'), ('five_star_rated', 'Classificação 5 Estrelas'), ('last_units', 'Últimas Unidades'), ('flash_sale', 'Oferta Relâmpago'), ('today_only', 'Somente Hoje'), ('gift_idea', 'Sugestão de Presente'), ('most_searched', 'Mais Procurado'), ('combo_deal', 'Oferta Combo'), ('online_only', 'Exclusivo Online'), ('ready_to_ship', 'Pronto para Envio'), ('pre_order', 'Pré-Venda')], max_length=282, null=True),
        ),
    ]
