# Generated by Django 5.1.3 on 2025-01-09 21:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_produto_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='capa_imagem',
            field=models.ImageField(default='capa.jpg', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='imagem',
            field=models.ImageField(default='vendedor.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
