# Generated by Django 5.1.3 on 2025-01-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_vendedor_capa_imagem_alter_vendedor_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='data_pedido',
            field=models.DateTimeField(),
        ),
    ]
