# Generated by Django 5.1.3 on 2025-01-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_produto_badges'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='badges',
        ),
    ]
