# Generated by Django 5.1.3 on 2025-01-10 18:34

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_remove_produto_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='badges',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('hot', 'Em Destaque'), ('new', 'Novo'), ('sale', 'Em Promoção'), ('bestseller', 'Mais vendido'), ('trending', 'Tendência'), ('recommended', 'Recomendado'), ('exclusive_deal', 'Oferta Exclusiva'), ('free_shipping', 'Frete Grátis'), ('best_price', 'Melhor Preço'), ('just_arrived', 'Recém-Chegado'), ('limited_edition', 'Edição Limitada'), ('organic', 'Orgânico'), ('handmade', 'Feito à Mão'), ('locally-made', 'Produzido Localmente'), ('warranty', 'Com Garantia'), ('certified', 'Certificado'), ('five-star-rated', '5 Estrelas'), ('last_units', 'Últimas Unidades'), ('flash_sale', 'Oferta Relâmpago'), ('today_only', 'Por tempo limitado'), ('gift_idea', 'Sugestão de Presente'), ('most_searched', 'Mais Procurado'), ('combo_deal', 'Combo'), ('online_only', 'Online'), ('ready_to_ship', 'Envio Imediato'), ('pre_order', 'Pré-venda')], max_length=282, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qtd_estoque',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
