# Generated by Django 5.1.4 on 2025-01-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_produto_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('desconto', models.IntegerField(default=1)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
