# Generated by Django 5.1.4 on 2025-01-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='core.coupon'),
        ),
    ]
