# Generated by Django 5.1.4 on 2025-01-13 20:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_pedidocarrinho_coupons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='data_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usos_atuais',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usos_maximos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='valor_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='desconto',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
