# Generated by Django 5.1.4 on 2025-01-13 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_coupon_options_coupon_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='data_pedido',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
