# Generated by Django 5.1.4 on 2025-01-14 22:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_pedidocarrinho_data_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='status_pagamento',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
