# Generated by Django 5.1.4 on 2025-01-15 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_couponusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
