# Generated by Django 5.1.4 on 2025-01-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_delete_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='num_fatura',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
