# Generated by Django 5.1.4 on 2025-01-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_pedidocarrinho_num_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='estado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
