# Generated by Django 5.1.4 on 2025-01-17 02:21

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_pedidocarrinho_cidade_pedidocarrinho_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='sku'),
        ),
    ]
