# Generated by Django 5.1.4 on 2025-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_pedidocarrinho_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='paypal_txn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='data_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='num_fatura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='status_pagamento',
            field=models.BooleanField(default=False),
        ),
    ]
