# Generated by Django 5.1.4 on 2025-01-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_pedidocarrinho_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='orderid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
