# Generated by Django 5.1.4 on 2025-01-21 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_pedidocarrinho_orderid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocarrinho',
            options={'verbose_name_plural': 'Pedidos'},
        ),
    ]
