# Generated by Django 5.1.4 on 2025-01-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_pedidocarrinho_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='orderid',
        ),
    ]
