# Generated by Django 5.1.4 on 2025-01-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_pedidocarrinho_orderid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenspedidocarrinho',
            options={'verbose_name_plural': 'Itens de Pedidos'},
        ),
    ]
