# Generated by Django 5.1.4 on 2025-01-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_itenspedidocarrinho_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='paypal_txn_id',
        ),
    ]
