# Generated by Django 5.1.4 on 2025-01-22 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_remove_pedidocarrinho_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='order_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
