# Generated by Django 5.1.4 on 2025-01-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_metodopagamento_coupon_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
