# Generated by Django 5.1.4 on 2025-01-26 22:16

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_endereco_latitude_endereco_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='orderid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix=''),
        ),
    ]
