# Generated by Django 5.1.4 on 2025-01-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_pedidocarrinho_desconto_pedidocarrinho_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='id_rastreamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidocarrinho',
            name='metodo_entrega',
            field=models.CharField(choices=[('delivery', 'Entrega'), ('pickup', 'Retirada')], default='delivery', max_length=100),
        ),
    ]
