# Generated by Django 5.1.4 on 2025-01-28 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_itenspedidocarrinho_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
