# Generated by Django 5.1.4 on 2025-01-28 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_pedidocarrinho_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedidocarrinho',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='itenspedidocarrinho',
            name='num_fatura',
        ),
        migrations.RemoveField(
            model_name='itenspedidocarrinho',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='itenspedidocarrinho',
            name='qtd',
        ),
        migrations.RemoveField(
            model_name='itenspedidocarrinho',
            name='status_produto',
        ),
        migrations.AddField(
            model_name='itenspedidocarrinho',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
