# Generated by Django 5.1.4 on 2025-01-28 04:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_remove_itenspedidocarrinho_imagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedidocarrinho',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='cep',
        ),
        migrations.AddField(
            model_name='itenspedidocarrinho',
            name='imagem',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itenspedidocarrinho',
            name='num_fatura',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itenspedidocarrinho',
            name='qtd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itenspedidocarrinho',
            name='status_produto',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='item',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=999999999),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=999999999),
        ),
    ]
