# Generated by Django 5.1.4 on 2025-01-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_remove_itenspedidocarrinho_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='cep',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
