# Generated by Django 5.1.4 on 2025-01-28 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_pedidocarrinho_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.produto'),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='qtd',
            field=models.IntegerField(default=1),
        ),
    ]
