# Generated by Django 5.1.4 on 2025-01-28 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_itenspedidocarrinho_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='core.produto'),
        ),
    ]
