# Generated by Django 5.1.4 on 2025-01-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_itenspedidocarrinho_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='imagem',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itenspedidocarrinho',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1.99, max_digits=10),
        ),
    ]
