# Generated by Django 5.1.4 on 2025-01-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_itenspedidocarrinho_imagem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name_plural': 'Lista de Produtos'},
        ),
        migrations.AddField(
            model_name='produto',
            name='fim_promocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='inicio_promocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='qtd_vendida',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
