# Generated by Django 5.1.4 on 2025-02-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_produto_options_produto_fim_promocao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_antigo',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
