# Generated by Django 5.1.4 on 2025-02-03 18:06

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_produto_preco_antigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='SKU'),
        ),
    ]
