# Generated by Django 5.1.4 on 2025-02-03 19:13

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_alter_pedidocarrinho_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='itenspedidocarrinho',
            name='orderid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix=''),
        ),
    ]
