# Generated by Django 5.1.4 on 2025-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_itenspedidocarrinho_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocarrinho',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='pedidos', to='core.coupon'),
        ),
    ]
