# Generated by Django 5.1.4 on 2025-02-04 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_remove_pedidocarrinho_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.endereco'),
        ),
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
