# Generated by Django 5.1.4 on 2025-02-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_pedidocarrinho_endereco_alter_pedidocarrinho_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
