# Generated by Django 5.1.4 on 2025-02-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_alter_pedidocarrinho_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocarrinho',
            name='informacoes_adicionais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
