# Generated by Django 5.1.4 on 2025-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_pedidocarrinho_informacoes_adicionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocarrinho',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
